services:
  - type: web
    name: data-mining-database-setup
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python database_setup.py
    envVars:
      - key: MONGODB_URI
        sync: false 